### ISSUE TITLE
Add documentation how to run

### ISSUE THREAD

**Issue by ablizorukov** [Job79/EasyTcp#21]
That's very important to describe how to run, the server should be listening and shouldn't just die after the run.

Beside adding while (true) (which is not in the doc also) maybe there are some ways to run and keep running it?

Also, please, add some examples

**Comment by Job79** [comment]
If you want to keep the server listener it must not get disposed.
This happens when calling .Dispose, or when using  the `using` statement and the server goes out of scope. Check out [EasyTcp3.Examples](https://github.com/Job79/EasyTcp/tree/master/EasyTcp3/EasyTcp3.Examples)

An alternative for a while loop is an infinite wait `Task.Delay(-1).Wait();`
Example:
```
using var server = new EasyTcpServer().Start(52520);
server.OnDataReceive += (sender, message) => Console.WriteLine(message.ToString());
Task.Delay(-1).Wait();
```


Did you see the EasyTcp.Examples folder? Feel free to ask when needing a specific example.
