### ISSUE TITLE
Can Connect local, but not from outside network

### ISSUE THREAD

**Issue by SonOfKorriban** [Job79/EasyTcp#66]
Servus from germany, again...

i am using your ActionServer and ActionClient. Both are fully functionally, if i initialize the Server with `server.Start(999)` and connect the client via `client.Connect("127.0.0.1", 999, TimeSpan.FromSeconds(1000));`.

But if i want to connect to a specific (public) ip address outside of the clients network, it throws an exception, because it's unable to find the server. Any Ideas why? Did i miss something?

**Comment by Job79** [comment]
Hello,

Here are some things that might help.
Did you port forward the server? Maybe check with an online port check tool (while the server is running)

Because you are using port 999, is the server run with root (or admin) privileges? This is needed for servers which use a port < 1024, you might want to use another port.

Are you giving a public ip to the `.Connect()` function? This should be the ip of the server. (curl or visit [api.ipify.org](https://api.ipify.org) on the server)

**Comment by SonOfKorriban** [comment]
Thank you very much! i got it now :)
