### ISSUE TITLE
Release v4

### ISSUE THREAD

**Issue by thijsk** [Job79/EasyTcp#70]
What is the current timeline for publishing the 4 version of EasyTcp as non-beta?
Are there any technical issues holding back a release, or is it just the lack of documentation?

Regards,
Thijs

**Comment by Job79** [comment]
Hello @thijsk,

The EasyTcp4 branch is still in beta because I forgot about this project and couldn't reproduce issue #68 

I was also struggling with the encrypted delimiter protocol, which is still not working. (see [afdd964](https://github.com/Job79/EasyTcp/commit/afdd9649b1ba2b69638bf1eaf547ad50e0075b76))
The issue looks like #68, but I can only reproduce it for the encrypted version (encrypted version is currently missing in EasyTcp4)
I am thinking about dropping the `EncryptedDelimiterProtocol` and releasing version 4.

It would also be nice to have some documentation before the next release.
I will write something when I have some motivation.

Regards,
Job79

**Comment by thijsk** [comment]
Hi @Job79 ,

Considering the performance of the delimiter protocol it seems fine to me to drop support for that in v4.
If I can find some time I'll take a look at that branch.

Thanks,
Thijs

**Comment by Job79** [comment]
Version 4.0 is released

**Comment by thijsk** [comment]
Thanks!
