### ISSUE TITLE
Received packets send by `SendLargeArray` contains invalid data/bytes

### ISSUE THREAD

**Issue by Gredys** [Job79/EasyTcp#71]
There is some problem with read bytes from message. Some bytes are replaced by other or even removed.

Example:
 - Send from client `client.SendLargeArray(buffer, false, false)` where buffer contains 40 bytes.
 - Receive packet on server with `OnDataReceive`. Resulting packet will contains only 36 bytes. I.e. 4 bytes was consumed somewhere in chain leading to corrupted data on the end.
 
 Another example:
  - Send from client `client.SendLargeArray(buffer, false, true)` where buffer contains 40 bytes.
  - Receive packet on server with `OnDataReceive`. Resulting packet will contains 40 bytes, but last two bytes were removed and two bytes [00, 00] were inserted at begning. Again - leading to corrupted data.
  
  In addition to all above. Using `SendLargeArray` results in instant disconnect from server after sending message.

**Comment by Job79** [comment]
The standard protocol used by EasyTcp (PrefixLenghtProtocol) stores the length of the message in the first 4 bytes.
Then when data is normally received, the first 4 bytes are used to determine the message length.

I assume that SendLargeArray is used to send an array and is received outside a receive event. 
This would let the standard protocol handle the message, which results in the first 4 bytes being removed (or the connection being dropped because of an invalid header)

The solution to this problem would be sending a small message (probably with some additional information) and then in the receive event would call the ReceiveLargeArray() function.
This would fix the problem because the standard protocol (PrefixLenght) isn't running for that connection inside the onReceive event.

See this example:
https://github.com/Job79/EasyTcp/blob/master/EasyTcp3/EasyTcp3.Examples/LargeArray/LargeArrayExample.cs
Note that when not using EasyTcp.Actions the ReceiveLargeArray function would be called inside the OnReceive event instead of the action function.

**Comment by Job79** [comment]
I am guessing the above comment was helpful, feel free to reopen this issue when this is not the case.
